server:
  port: 8080
spring:
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/campsite"
    username: localdev
    password: localdev
  liquibase:
    enabled: true
    change-log: "classpath:liquibase/changelog-master.xml"
management:
  endpoints:
    web:
      exposure:
        include: "*"
